Fix gun init fail on nodejs
When using sea on node.js it will fail at the init stage:
/Users/xxx/node_modules/gun/sea.js:1355
    Gun.on('opt', function(at){
        ^

TypeError: Cannot read property 'on' of undefined
    at /Users/xxx/node_modules/gun/sea.js:1355:9
    at /Users/xxx/node_modules/gun/sea.js:11:7
    at /Users/xxx/node_modules/gun/sea.js:1580:5
    at Object.<anonymous> (/Users/geliz/node_modules/gun/sea.js:1581:2)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)

with call from
const Gun = require("gun/gun");
require("gun/sea");
const Sea = Gun.SEA;